version: "3.9"
name: nginx-proxy
services:
  nginx_proxy:
    image: ${NGINX_IMAGE}:${NGINX_VERSION}
    #build: .
    container_name: nginx-proxy
    restart: always
    deploy:
      #replicas: 1
      resources:
        limits:
          memory: 128M
    restart: always
    volumes:
      - "${PWD}/volumes/nginx_configuration/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/volumes/nginx_configuration/proxy_params:/etc/nginx/proxy_params"
      - "${PWD}/volumes/nginx_configuration/custom:/etc/nginx/custom"
      - "${PWD}/volumes/nginx_configuration/ssl:/etc/nginx/ssl"
      - "${PWD}/volumes/nginx_configuration/sites-available:/etc/nginx/sites-available"
      - "${PWD}/volumes/nginx_configuration/sites-enabled:/etc/nginx/sites-enabled"
    networks:
      - web
    ports:
      - "80:8080"
      - "443:8443"
networks:
  web:
    external: true
    name: web
