version: "3"

services:
  ariang:
    image: ${ARIANG_IMAGE}:${ARIANG_VERSION}
    container_name: ariang
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: ariang
    ports:
      - 8780:8080
      - 6800:6800
    networks:
      - web
    volumes:
      - ${PWD}/volumes/ariang_data:/aria2/data
      - ${PWD}/volumes/ariang_config:/aria2/conf
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=${RPC_SECRET}
      - ARIA2RPCPORT=8780
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true