version: "3.9"
name: postgresql
services:
  postgresql:
    image: ${POSTGRESQL_IMAGE}:${POSTGRESQL_VERSION}
    #build: .
    container_name: postgresql
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    entrypoint: ["/start-postgres.sh"]
    volumes:
      - "$PWD/start-postgres.sh:/start-postgres.sh"
      - "$PWD/volumes/postgresql_data:/var/lib/postgresql/data"
    networks:
      - web
    ports:
      - "5432:5432"
networks:
  web:
    external: true
    name: web
