# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - /etc/prometheus/rules/*.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: "prometheus"
  #
  #  # metrics_path defaults to '/metrics'
  #  # scheme defaults to 'http'.
  #
  #  static_configs:
  #    - targets: ["localhost:9090"]
  #
  #- job_name: "prometheus"
  #  scrape_interval: 120s
  #  static_configs:
  #    - targets: ["localhost:9090", "cadvisor:8080", "localhost:9100"]

  #- job_name: "prometheus"
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: ["localhost:9090"]

  - job_name: "website-monitoring-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "website-monitoring-icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  #- job_name: 'prometheus-mysql'
  #  static_configs:
  #    - targets: ['localhost:9091']

  #- job_name: "postgres-exporter"
  #  static_configs:
  #    - targets: ["localhost:9187", "localhost:9188"]
