version: "3.9"
name: traccar
services:
  traccar:
    image: ${TRACCAR_IMAGE}:${TRACCAR_VERSION}
    #build: .
    hostname: traccar
    container_name: traccar
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: always
    networks:
      - web
    environment:
      TZ: Asia/Jakarta
    volumes:
      - "${PWD}/volumes/traccar_data/logs:/opt/traccar/logs"
      - "${PWD}/volumes/traccar_data/config/traccar.xml:/opt/traccar/conf/traccar.xml"
    ports:
      - "8088:8082"
      - "5023:5023"
      - "5023:5023/udp"
      - "5055:5055"
      - "5055:5055/udp"
      #- "5000-5150:5000-5150"
      #- "5000-5150:5000-5150/udp"
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  #traccardb:
  #  image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
  #  #build: .
  #  hostname: traccar-db
  #  container_name: traccardb
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 512M
  #  restart: always
  #  #command: --default-authentication-plugin=mysql_native_password
  #  environment:
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #    MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
  #    TZ: ${MYSQL_TIMEZONE}
  #  volumes:
  #    - "${PWD}/volumes/mysql_data:/var/lib/mysql"
  #  networks:
  #    - web
  #  ports:
  #    - 3306:3306
  #  privileged: true
  #  logging:
  #    driver: json-file
  #    options:
  #      max-size: "10m"
  #      max-file: "3"
networks:
  web:
    external: true
    name: web
