version: "3.9"
name: pgadmin4
services:
  pgadmin4:
    image: ${PGADMIN_IMAGE}:${PGADMIN_VERSION}
    #build: .
    container_name: pgadmin4
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "${PWD}/volumes/pgadmin_data:/var/lib/pgadmin"
    networks:
      - web
    ports:
      - "8880:80"
networks:
  web:
    external: true
    name: web
