version: "3.9"
name: vaultwarden
services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}:${VAULTWARDEN_VERSION}
    hostname: vaultwarden
    container_name: vaultwarden
    deploy:
      resources:
        limits:
          memory: 128M
    restart: unless-stopped
    environment:
      DOMAIN: "${DOMAIN_URL}"
      TZ: Asia/Jakarta
    volumes:
      - ${PWD}/volumes/vw_data/:/data/
    ports:
      - 8085:80
    networks:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  web:
    external: true
    name: web