version: "3.9"
name: cloudbeaver
services:
  cloudbeaver:
    image: ${CLOUDBEAVER_IMAGE}:${CLOUDBEAVER_VERSION}
    #build: .
    container_name: cloudbeaver
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - "$PWD/volumes/cloudbeaver_data:/opt/cloudbeaver/workspace"
    networks:
      - web
    ports:
      - "8978:8978"
networks:
  web:
    external: true
    name: web
