version: "3.9"
name: mongodb
services:
  mongodb:
    image: ${MONGODB_IMAGE}:${MONGODB_VERSION}
    #build: .
    container_name: mongodb
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "$PWD/volumes/mongodb_data:/data/db"
    networks:
      - web
    ports:
      - "27017:27017"
networks:
  web:
    external: true
    name: web
