version: '3.8'
services:
  jenkins:
    build:
      context: .
    #image: jenkins/jenkins:2.516.1-jdk21
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    networks:
      - web
    environment:
      - TZ=Asia/Jakarta
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ${PWD}/volumes/jenkins_data:/var/jenkins_home
      - ${PWD}/volumes/jenkins_docker_certs:/certs/client:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  web:
    external: true
