version: "3.9"
name: portainer
services:
  portainer:
    image: ${PORTAINER_IMAGE}:${PORTAINER_VERSION}
    #build: .
    hostname: portainer
    container_name: portainer
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      TZ: Asia/Jakarta
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/volumes/portainer_data:/data"
    networks:
      - web
    ports:
      - "9443:9443"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  web:
    external: true
    name: web