version: "3.9"
name: mysql
services:
  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
    container_name: mysql
    hostname: mysql
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      TZ: ${MYSQL_TIMEZONE}
    volumes:
      - "${PWD}/volumes/mysql_data:/var/lib/mysql"
    networks:
      - web
    ports:
      - 3306:3306
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  web:
    external: true
    name: web