version: "3.9"
name: minio
services:
  minio:
    image: ${MINIO_IMAGE}:${MINIO_VERSION}
    #build: .
    hostname: minio
    container_name: minio
    restart: always
    #user: "${UID}:${GID}"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - "$PWD/volumes/minio_data:/data"
    networks:
      - web
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${CONFIG_MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${CONFIG_MINIO_ROOT_PASSWORD}"
      MINIO_BROWSER_REDIRECT_URL: "${CONFIG_MINIO_BROWSER_REDIRECT_URL}"
      MINIO_SERVER_URL: "${CONFIG_MINIO_SERVER_URL}"
      CONSOLE_SECURE_TLS_REDIRECT: "${CONFIG_CONSOLE_SECURE_TLS_REDIRECT}"
    command: ["server", "/data", "--console-address", ":9001"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  web:
    external: true
    name: web
