version: "3.9"
name: mysql-phpmyadmin
services:
  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
    #build: .
    container_name: mysql
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      TZ: ${MYSQL_TIMEZONE}
    volumes:
      - "${PWD}/volumes/mysql_data:/var/lib/mysql"
    networks:
      - web
    ports:
      - 3306:3306
  #phpmyadmin_proxy:
  #  image: ${NGINX_IMAGE}:${NGINX_VERSION}
  #  #build: .
  #  container_name: phpmyadmin-proxy
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 256M
  #  restart: always
  #  volumes:
  #    - "${PWD}/volumes/nginx_configuration/default.conf:/etc/nginx/conf.d/default.conf"
  #  networks:
  #    - web
  #  ports:
  #    - "9880:80"
  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_VERSION}
    #build: .
    container_name: phpmyadmin
    #depends_on:
    #  - phpmyadmin_proxy
    restart: always
    environment:
      PMA_ARBITRARY: ${PHPMYADMIN_ARBITRARY}
      PMA_HOST: ${PHPMYADMIN_MYSQL_HOST}
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - web
    ports:
      - "8000:80"
      #- "9000:9000"
networks:
  web:
    external: true
    name: web
